name: Run Omega Analyzer

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Omega Analyzer
        uses: actions/checkout@v4
        with:
          repository: ossf/alpha-omega
          path: alpha-omega
          sparse-checkout: |
            omega/analyzer

      - name: Build/run container
        run: |
          cd ./alpha-omega/omega/analyzer
          ./build.sh
          docker run --rm -it -v ./results:/opt/export/github openssf/omega-toolshed:latest

